"""Add custom_content to chat_history

Revision ID: cb992240cd5f
Revises: 3eebd422ce77
Create Date: 2026-02-19 13:15:34.847904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb992240cd5f'
down_revision: Union[str, None] = '3eebd422ce77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('custom_content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'custom_content')
    # ### end Alembic commands ###
