"""Add feast selected meals and snapshot

Revision ID: 3eebd422ce77
Revises: bb3a62528d9f
Create Date: 2026-02-17 11:10:27.120800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eebd422ce77'
down_revision: Union[str, None] = 'bb3a62528d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feast_configs', sa.Column('selected_meals', sa.JSON(), nullable=True))
    op.add_column('feast_configs', sa.Column('original_diet_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feast_configs', 'original_diet_snapshot')
    op.drop_column('feast_configs', 'selected_meals')
    # ### end Alembic commands ###
