"""add_meal_adjustment_fields

Revision ID: 10d69ccc858f
Revises: d8df817ca385
Create Date: 2026-02-13 09:49:58.850070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10d69ccc858f'
down_revision: Union[str, None] = 'd8df817ca385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.alter_column('food_items', 'serving_size_g',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('food_items', 'region',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('food_items', 'vector_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_food_items_fdc_id'), 'food_items', ['fdc_id'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.alter_column('food_logs', 'meal_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('meal_plans', sa.Column('is_user_adjusted', sa.Boolean(), nullable=True))
    op.add_column('meal_plans', sa.Column('adjustment_note', sa.String(), nullable=True))
    op.alter_column('meal_plans', 'feast_notes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Feast Mode per-meal notes',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('meal_plans', 'feast_notes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Feast Mode per-meal notes',
               existing_nullable=True)
    op.drop_column('meal_plans', 'adjustment_note')
    op.drop_column('meal_plans', 'is_user_adjusted')
    op.alter_column('food_logs', 'meal_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_fdc_id'), table_name='food_items')
    op.alter_column('food_items', 'vector_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('food_items', 'region',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('food_items', 'serving_size_g',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    # ### end Alembic commands ###
