"""Add feast_workout_data columns

Revision ID: bb3a62528d9f
Revises: 3a5eb5a01e8f
Create Date: 2026-02-16 10:38:32.879391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3a62528d9f'
down_revision: Union[str, None] = '3a5eb5a01e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feast_configs', sa.Column('feast_workout_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feast_configs', 'feast_workout_data')
    # ### end Alembic commands ###
