"""add_change_reason_to_meal_plan_history

Revision ID: 3a5eb5a01e8f
Revises: 10d69ccc858f
Create Date: 2026-02-13 10:32:18.219635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5eb5a01e8f'
down_revision: Union[str, None] = '10d69ccc858f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_history', sa.Column('change_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan_history', 'change_reason')
    # ### end Alembic commands ###
